# ------------------------------------------------------------------ #
#                                                                    #
#           SymPy CI script for Github Actions                       #
#                                                                    #
#   Run on the release branch and builds the release artifacts.      #
#                                                                    #
# ------------------------------------------------------------------ #

name: release
env:
  release_branch: 1.8
  release_version: 1.8
on:
  push:
    branches:
      - {{ env.release_branch }}
  pull_request:
    branches:
      - {{ env.release_branch }}
jobs:

  # -------------------- Build artifacts --------------------------- #

  build:

    runs-on: ubuntu-20.04
    steps:
      # Check out with full git history for authors check:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: release/ci_release_script.sh {{ env.release_version }}

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: release-{{ env.release_version }}
