# ------------------------------------------------------------------ #
#                                                                    #
#           SymPy CI script for Github Actions                       #
#                                                                    #
#   Run on the release branch and builds the release artifacts.      #
#                                                                    #
# ------------------------------------------------------------------ #

name: release
on:
  push:
    branches:
      - 1.8
  pull_request:
    branches:
      - 1.8
jobs:

  # -------------------- Build artifacts --------------------------- #

  build:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: sudo apt-get install -y git
      - run: git clone https://github.com/sympy/sympy.git
      - run: git checkout 1.8
        working-directory: sympy

      - run: release/ci_release_script.sh 1.8
        working-directory: sympy

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: sympy/release-1.8
